"""changes the artist column name to artist_name columm

Revision ID: 2c6e13f4a181
Revises: 1ad3ba6235a3
Create Date: 2024-06-13 02:28:11.200318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6e13f4a181'
down_revision: Union[str, None] = '1ad3ba6235a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
