"""changes the artist column name

Revision ID: c832a7b07568
Revises: 2c6e13f4a181
Create Date: 2024-06-13 02:30:10.085984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c832a7b07568'
down_revision: Union[str, None] = '2c6e13f4a181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('artist', sa.VARCHAR(), nullable=True))
    op.drop_column('albums', 'artist_name')
    # ### end Alembic commands ###
