"""changes the __rep__ to artist_name

Revision ID: e701452b74e5
Revises: c832a7b07568
Create Date: 2024-06-13 16:10:56.890689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e701452b74e5'
down_revision: Union[str, None] = 'c832a7b07568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'albums', type_='foreignkey')
    # ### end Alembic commands ###
